version: '3'

services:
  vscode-ide:
    build: .
    ports:
      - '8000:8080'
    volumes:
      - '$PWD:/workspace'
    environment:
      PASSWORD: <password>
    restart: always
    user: '0:0'
